// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness_app/test/modules/meals/api/datasources/meals_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness_app/modules/meals/api/api_client/meals_api_client.dart'
    as _i3;
import 'package:super_fitness_app/modules/meals/data/models/response/meals_details_dto.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMealsDetailsDto_0 extends _i1.SmartFake
    implements _i2.MealsDetailsDto {
  _FakeMealsDetailsDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MealsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealsApiClient extends _i1.Mock implements _i3.MealsApiClient {
  @override
  _i4.Future<_i2.MealsDetailsDto> getMeals(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMeals, [id]),
            returnValue: _i4.Future<_i2.MealsDetailsDto>.value(
              _FakeMealsDetailsDto_0(this, Invocation.method(#getMeals, [id])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.MealsDetailsDto>.value(
              _FakeMealsDetailsDto_0(this, Invocation.method(#getMeals, [id])),
            ),
          )
          as _i4.Future<_i2.MealsDetailsDto>);
}
