// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qFN2WXEPWFySGFUDsS1KoDqcilSgkTc',
    appId: '1:289966024088:web:32bd8cf86141e8d83a37ed',
    messagingSenderId: '289966024088',
    projectId: 'fitness-app-56523',
    authDomain: 'fitness-app-56523.firebaseapp.com',
    storageBucket: 'fitness-app-56523.firebasestorage.app',
    measurementId: 'G-2MJRMCQ919',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvb_B8ZCfKLr1yNgIUk4-9-NwEai2OeeU',
    appId: '1:289966024088:android:68cf9d1ac11346dd3a37ed',
    messagingSenderId: '289966024088',
    projectId: 'fitness-app-56523',
    storageBucket: 'fitness-app-56523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJG2DSdhKTdDOt_8P1UuAneT3vROB7Mxg',
    appId: '1:289966024088:ios:cb73b1978dce03a73a37ed',
    messagingSenderId: '289966024088',
    projectId: 'fitness-app-56523',
    storageBucket: 'fitness-app-56523.firebasestorage.app',
    iosBundleId: 'com.example.superFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJG2DSdhKTdDOt_8P1UuAneT3vROB7Mxg',
    appId: '1:289966024088:ios:cb73b1978dce03a73a37ed',
    messagingSenderId: '289966024088',
    projectId: 'fitness-app-56523',
    storageBucket: 'fitness-app-56523.firebasestorage.app',
    iosBundleId: 'com.example.superFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7qFN2WXEPWFySGFUDsS1KoDqcilSgkTc',
    appId: '1:289966024088:web:02e0e31075e133e73a37ed',
    messagingSenderId: '289966024088',
    projectId: 'fitness-app-56523',
    authDomain: 'fitness-app-56523.firebaseapp.com',
    storageBucket: 'fitness-app-56523.firebasestorage.app',
    measurementId: 'G-NQZZZ8ZPW8',
  );
}
