// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness_app/test/modules/meals/data/repositories/meals_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness_app/config/base/base_response.dart' as _i5;
import 'package:super_fitness_app/modules/meals/data/datasources/meals_remote_data_source.dart'
    as _i3;
import 'package:super_fitness_app/modules/meals/data/models/response/meals_details_dto.dart'
    as _i6;
import 'package:super_fitness_app/modules/meals/domain/entities/meals_details_entity.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMealsDetailsEntity_0 extends _i1.SmartFake
    implements _i2.MealsDetailsEntity {
  _FakeMealsDetailsEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MealsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealsRemoteDataSource extends _i1.Mock
    implements _i3.MealsRemoteDataSource {
  @override
  _i4.Future<_i5.BaseResponse<_i6.MealsDetailsDto>> getMeals(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#getMeals, [mealId]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.MealsDetailsDto>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.MealsDetailsDto>>(
                    this,
                    Invocation.method(#getMeals, [mealId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.BaseResponse<_i6.MealsDetailsDto>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.MealsDetailsDto>>(
                    this,
                    Invocation.method(#getMeals, [mealId]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.MealsDetailsDto>>);
}

/// A class which mocks [MealsDetailsDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealsDetailsDto extends _i1.Mock implements _i6.MealsDetailsDto {
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.MealsDetailsEntity toDomain() =>
      (super.noSuchMethod(
            Invocation.method(#toDomain, []),
            returnValue: _FakeMealsDetailsEntity_0(
              this,
              Invocation.method(#toDomain, []),
            ),
            returnValueForMissingStub: _FakeMealsDetailsEntity_0(
              this,
              Invocation.method(#toDomain, []),
            ),
          )
          as _i2.MealsDetailsEntity);
}
