// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness_app/test/modules/meals/presentation/food_details/cubit/food_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness_app/config/base/base_response.dart' as _i5;
import 'package:super_fitness_app/modules/meals/domain/entities/meals_details_entity.dart'
    as _i6;
import 'package:super_fitness_app/modules/meals/domain/repositories/meals_repo.dart'
    as _i2;
import 'package:super_fitness_app/modules/meals/domain/use_cases/get_meals_details_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMealsRepo_0 extends _i1.SmartFake implements _i2.MealsRepo {
  _FakeMealsRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetMealsDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealsDetailsUseCase extends _i1.Mock
    implements _i3.GetMealsDetailsUseCase {
  @override
  _i2.MealsRepo get mealsRepo =>
      (super.noSuchMethod(
            Invocation.getter(#mealsRepo),
            returnValue: _FakeMealsRepo_0(this, Invocation.getter(#mealsRepo)),
            returnValueForMissingStub: _FakeMealsRepo_0(
              this,
              Invocation.getter(#mealsRepo),
            ),
          )
          as _i2.MealsRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.MealsDetailsEntity>> call(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [mealId]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.MealsDetailsEntity>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.MealsDetailsEntity>>(
                    this,
                    Invocation.method(#call, [mealId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.BaseResponse<_i6.MealsDetailsEntity>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.MealsDetailsEntity>>(
                    this,
                    Invocation.method(#call, [mealId]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.MealsDetailsEntity>>);
}
